"""Initial migration - existing schema

Revision ID: 7345d293f5e3
Revises: 
Create Date: 2025-07-18 23:20:12.209784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7345d293f5e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_updates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ticket_updates_ticket_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tickets', ['ticket_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_updates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ticket_updates_ticket_id_fkey'), 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
